version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sim_play2Project
  gitServerName: sim_github
  gitUrl: https://github.com/SimonHanischSAG/Sim_play2Project
  gitUsername: SimonHanischSAG
  gitBranch: main
