version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sim_play2Project
  gitServerName: sim_github
  gitUrl: https://github.com/SimonHanischSAG/Sim_play2Project
  gitUsername: SimonHanischSAG
  gitBranch: main
services:
- serviceName: project.sim_play2.integrations:testAnywhere
  packages:
  - name: Sim_play2Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.sim_play2.integrations:testAnywhere2
  packages:
  - name: Sim_play2Project
    version: "1.0"
